import type { Metadata } from "next";
import "../globals.css";
import { Navbar } from "@/components/frontend/Navbar";
import { Footer } from "@/components/frontend/Footer";
import { AppProvider } from "../../lib/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased flex flex-col`}>
        <AppProvider>
          <div className="flex flex-col">
            <header>
              <Navbar />
            </header>
            <main className="min-h-[90vh]">{children}</main>
            <Footer />
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
